Replace Russian version with nondead analog
bnjbvr/rouille pull request #51
Opened 2022-10-05 18:43 UTC by Sanceilaks

2022-10-05 18:55 UTC, bnjbvr requested changes
There are a bit too many references to gods for my taste in the README file, and a bit too many insults in the code. Can you change that?

2022-10-05 19:04 UTC, Sanceilaks commented
No problems, 10 minutes

2022-10-05 19:17 UTC, Sanceilaks commented
As for "God", this is an old Russian meme "we are Russians, God is with us!". This is not meant to belittle or insult others, just a joke.
Insults removed

2022-10-08 14:02 UTC, bnjbvr commented on README.md
> +- Russian: [Ржавый]([https://github.com/FluxIndustries/rzhavchina](https://github.com/Sanceilaks/rzhavchina))
```suggestion
- Russian: [Ржавый](https://github.com/Sanceilaks/rzhavchina)
```

2022-10-08 14:05 UTC, merged